Bootstrap: docker
From: ubuntu:focal

%labels

AUTHOR Mainak

%post
 
apt update
apt upgrade -y
apt-get -y install net-tools
apt-get -y install curl wget \
    nano vim python3-pip python3-venv \
    build-essential python3-dev \
    git

pip3 install numpy \
    pandas \
    jsonmerge \
    jsonlines \
    elasticsearch \
    parquet

